### ISSUE TITLE
Won't submit properly

### ISSUE THREAD

**Issue by pleugemors** [learn-co-curriculum/programming-univbasics-nds-nds-to-insight-with-flexibility-lab#2]
code passes tests with 19 examples and zero failures, but when I type learn submit it does not unlock next lesson button

**Comment by sgharms** [comment]
This is probably something that we need live help to debug.

Hi there,


This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
